# Generated by Django 5.0.7 on 2024-11-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(blank=True, choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('fish', 'Fish'), ('snake', 'snake')], max_length=100, null=True),
        ),
    ]
